In [1]:
import numpy as np

In [3]:
arr = np.array([1,2,3])

In [5]:
matrix = np.array([[1,2,3],[2,3,4],[3,4,5]])

In [6]:
matrix

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [12]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
maxii = np.linspace(0,10)
maxii

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [25]:
np.random.rand(3)

array([0.99597183, 0.604667  , 0.96968177])

In [28]:
np.random.randn(5,5)

array([[ 0.91206453,  0.63728857,  0.86546169,  0.12741698, -0.21967587],
       [ 0.02580338, -2.78058469, -1.4028553 , -3.87687412, -0.14645944],
       [-2.01666042,  2.23376017, -1.13096175, -0.3000661 , -1.25659774],
       [-1.24753071,  2.41660506,  0.62607502, -0.04362973,  0.61015668],
       [ 1.11069346, -0.95006698,  0.75339991,  0.069544  ,  0.87112797]])

In [55]:
np.random.randint(10,100,10)

array([44, 97, 35, 73, 30, 89, 10, 21, 43, 13])

In [56]:
arr

array([1, 2, 3])

In [59]:
arr.reshape(3,1)

array([[1],
       [2],
       [3]])

In [64]:
maxii.max()

10.0

In [65]:
maxii.argmin()

0

In [66]:
maxii.argmax()

49

In [67]:
maxii.dtype

dtype('float64')

In [73]:
arrRef = np.arange(1,11)

In [74]:
arrRef[4]

5

In [75]:
arrRef

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
arrRef[4:]

array([ 5,  6,  7,  8,  9, 10])

In [78]:
arrRef[:5]

array([1, 2, 3, 4, 5])

In [79]:
arrRef.argmax()

9

In [80]:
arrRef[0:5]= 100

In [81]:
arrRef

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [83]:
arrRef%3

array([1, 1, 1, 1, 1, 0, 1, 2, 0, 1], dtype=int32)

In [86]:
import numpy as np

In [87]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [88]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [89]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [90]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [91]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [92]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [96]:
np.random.random(1)

array([0.58494738])

In [97]:
np.random.randn(25)

array([ 0.2929006 ,  0.31522449, -0.52669244,  1.07449864,  1.3694325 ,
       -1.108623  , -0.51018977, -1.07244471,  1.13701871, -0.10867625,
       -0.00579589,  0.20043798, -0.14413927,  0.72130282,  0.37211604,
       -0.49404036,  0.97089635,  0.29673994,  0.08705413,  0.41943042,
        1.66967003, -1.14879586, -0.19648218,  0.03098398,  1.32406466])

In [105]:
(np.arange(1,101)/100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [108]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [110]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [111]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [112]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [113]:
mat[4]

array([21, 22, 23, 24, 25])

In [115]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [116]:
mat.sum()

325

In [118]:
mat.std()

7.211102550927978

In [121]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [161]:
array = np.random.randint(1,26,25)
print(array)
indices = np.random.randint(1,25,5)


[14 24  8 11 13 10 10 22 15  3  2 19  6  2 25 18 19 25 17  5 21  6  2  7
 13]


In [163]:
print(np.unique(indices))
array[np.unique(indices)]

[ 1  5 15 16 18]


array([24, 10, 18, 19, 17])

In [164]:
array

array([14, 24,  8, 11, 13, 10, 10, 22, 15,  3,  2, 19,  6,  2, 25, 18, 19,
       25, 17,  5, 21,  6,  2,  7, 13])

In [165]:
array[np.unique(indices)]+=1

In [168]:
array

array([14, 25,  8, 11, 13, 11, 10, 22, 15,  3,  2, 19,  6,  2, 25, 19, 20,
       25, 18,  5, 21,  6,  2,  7, 13])

In [233]:
A = np.random.randint(0,10,(3,4,4,3))


In [247]:
sumA = A.sum(axis=(-1,-2))

In [248]:
sumA

array([[55, 48, 69, 54],
       [59, 51, 37, 49],
       [40, 51, 68, 46]])

In [249]:
A[0,1,:,:]

array([[5, 4, 4],
       [4, 0, 5],
       [0, 3, 7],
       [4, 4, 8]])

In [270]:
swaparray = np.random.randint(1,10,(3,3))
swaparray

array([[7, 4, 8],
       [5, 4, 4],
       [4, 1, 3]])

In [278]:
swaparray[[0,1]]= swaparray[[1,0]]

In [279]:
swaparray

array([[7, 4, 8],
       [5, 4, 4],
       [4, 1, 3]])

In [288]:
zing = np.random.random(9)
zing

array([0.75706451, 0.53054147, 0.75264863, 0.28483181, 0.52610789,
       0.35256895, 0.54884495, 0.13240097, 0.45736064])

In [289]:
def 

array([-0.24293549, -0.46945853, -0.24735137, -0.71516819, -0.47389211,
       -0.64743105, -0.45115505, -0.86759903, -0.54263936])

SyntaxError: invalid syntax (<ipython-input-286-46471357a0d9>, line 1)